### ISSUE TITLE
First!! Here have some ideas:

### ISSUE THREAD

**Issue by DDZiroWan** [seymourimadeit/Big-Brain#1]
Rabbits should breed like pigs, or more (4-8 instead of 1-5?).

All animals should breed on their own if in the wild or if well kept, that is, if there isn't more than 6 (?) animals of the same type near (16 blocks?) them and some of them need food sources to breed this way.

- Pig: Any dropped food or a composter (consumes 1 layer?)
- Sheep: Grass block
- Cow: Tall grass (doesn't consume it)
- Chicken: Dirt, grass block, podzol (doesn't consume either)
- Rabbit: Dandelions or crops (consumed)
- Cod: Kelp tops (consumed) (less ugly oceans?)
- Salmon: Kelp tops (consumed) or Seagrass (not consumed)
- Mooshroom: Mycelium (not consumed)

Cats, tamed wolves, donkeys, horses, llamas and pandas should only be bred manually.
Foxes, wild wolves, ocelots, parrots, polar bears, dolphins don't need food sources (since they aren't useful in farms anyway) to breed naturally.

**Comment by seymourimadeit** [comment]
Suggestions should not be posted on the github, instead they should be on the discord.
