### ISSUE TITLE
Piglin Brute Buckler crash.

### ISSUE THREAD

**Issue by Hail99wasd** [seymourimadeit/Big-Brain#13]
[crash-2021-05-05_10.33.41-server.txt](https://github.com/seymourimadeit/Big-Brain/files/6426462/crash-2021-05-05_10.33.41-server.txt)
Happens whenever a Piglin Brute attempts to use the Buckler.

**Comment by Hail99wasd** [comment]
Crash also happens when I attempted to use a buckler.

**Comment by Hail99wasd** [comment]
After using the buckler I'm no longer able to join the server.

**Comment by seymourimadeit** [comment]
release 1.2.3 should fix this
