### ISSUE TITLE
Buckler Crash when using it on mobs and mobs using it on players.

### ISSUE THREAD

**Issue by RangerSpade** [seymourimadeit/Big-Brain#16]
I own a modded minecraft server where this mod is used, every time som
[crash-2021-05-07_20.46.26-server.txt](https://github.com/seymourimadeit/Big-Brain/files/6446449/crash-2021-05-07_20.46.26-server.txt)
eone uses the buckler it crashes their game. Not sure why.

**Comment by seymourimadeit** [comment]
You're on version 1.2.2 which is outdated, the newest version should fix this.
