### ISSUE TITLE
Ticking entity crash in dedicated forge server

### ISSUE THREAD

**Issue by ohhhhhmyg0d** [seymourimadeit/Big-Brain#19]
[crash-2021-10-16_21.52.42-server.txt](https://github.com/seymourimadeit/Big-Brain/files/7359014/crash-2021-10-16_21.52.42-server.txt)
[crash-2021-10-17_13.10.21-server.txt](https://github.com/seymourimadeit/Big-Brain/files/7359016/crash-2021-10-17_13.10.21-server.txt)

ticking entity crash in a dedicated server, originally posted this on the epic fight mod issue tracker but the dev concluded that it was caused by big brain.

**Comment by seymourimadeit** [comment]
If I'm gonna be honest here this seems like an issue with the epic fight mod not checking if a target is null or not in its chasinggoal class. I could be wrong though.
