### ISSUE TITLE
[1.18.1] Server Crashes when attempting to load this mod

### ISSUE THREAD

**Issue by NJL5390** [seymourimadeit/Big-Brain#22]
Big Brain Version: 1.4.0
Forge Version: 39.0.59
Minecraft Version: 1.18.1
Crash Report: https://gist.github.com/NJL5390/4edfbe59ab1dfda5715cb4e168e14471

Hi,
Just reporting this to let you know that I've have been having trouble testing this mod on my modded server in that the server just crashes when attempting to load this mod.

If I remove this mod then the server stops crashing.

I also just want to say that I love all the interesting changes and additions that this mod makes to mob ai and it has quickly become one of my favourites! So thank you for making it!

**Comment by seymourimadeit** [comment]
Right now this crash can be mitigated by going on forge 39.0.56 or any lower version.
