### ISSUE TITLE
[1.16.5] AI Incompatibility with Crossbow AI providing mods, causing Crossbow holding enemies to be unable to fire due to inconsistent Goal ticking

### ISSUE THREAD

**Issue by Kaleidio** [seymourimadeit/Big-Brain#23]
Illagers with crossbows will have trouble finding their target, causing them to rapidly reload the weapon every time they switch between goals.  This makes it so they never load the arrow successfully at all, and thus never end up firing.  This is affected by Recruits mod, and only happens when both are installed at once

**Comment by seymourimadeit** [comment]
Recruits is closed source, not much I could do to fix it. Also we don't support 1.16.5 anymore.
