### ISSUE TITLE
Crash when attempting to view Buckler recipe with JEI

### ISSUE THREAD

**Issue by cosmicgelatin** [seymourimadeit/Big-Brain#25]
mousing over a buckler item with JEI and pressing the "show recipe" keybind leads to a crash, says something about "INGOTS_GOLD". I can attach a log if the issue isn't replicable.

**Comment by seymourimadeit** [comment]
fixed in dev

**Comment by seymourimadeit** [comment]
Also the buckler doesn't have a recipe unless you added a custom one.
