### ISSUE TITLE
[1.16.5] Cats will attack villagers regardless of "all mobs attack villagers" configuration settings.

### ISSUE THREAD

**Issue by Kaleidio** [seymourimadeit/Big-Brain#27]
I understand that 1.16.5 support is dropped but this behaviour is strangely consistent for me.

**Comment by seymourimadeit** [comment]
Yeah I'm gonna be honest here this is probably caused by a different mod, because this mod doesn't add anything that makes cats attack villagers, and the all mobs attack villagers config setting only affects hostile mobs.

**Comment by Kaleidio** [comment]
it's strange because when I removed Big Brain, the issue disappeared.  I will continue to investigate to see if I can find the exact incompatibility but for now, please do not close this, as I can confirm it is Big Brain related.

**Comment by seymourimadeit** [comment]
I have reopened this issue, but if this issue can't be effectively recreated on 1.18 then I will close it.

**Comment by Kaleidio** [comment]
closing issue, discovery of some other mod was found
