### ISSUE TITLE
Animal night find a shelter switch? MC 1.16

### ISSUE THREAD

**Issue by Accidey** [seymourimadeit/Big-Brain#28]
Can you do an animal night, find a shelter switch? Because I found that all animals run around aimlessly at night. I know that I can add animal blacklists to the config file myself, but I also added animal mods, which is a waste of time to adapt. Thank you for seeing this, this is one of my suggestions, I hope you can take it.

**Comment by seymourimadeit** [comment]
Already exists and don't post suggestions to this github.
