### ISSUE TITLE
[1.18.2 - Big Brain V1.5.3 Forge V40.1.80] - Spyglass is Crashing Player from Modded Server (Doesn't Crash Client).

### ISSUE THREAD

**Issue by Jusey1** [seymourimadeit/Big-Brain#31]
Okay, this is just the weirdest bug I have ever witness and I couldn't even get it reproduced, so I'm not sure on exactly why it was only happening to me on my own server but it's a thing and I have server logs which explains what was happening code-wise at least, and "Big Brain" was mentioned enough times that I decided to remove it and by doing so, the bug is fixed and no longer happening, so here I am.

Essentially, what was happening that if ANYONE uses a Spyglass while I am near them, I would crash out of the server. My client won't crash and server won't crash, so I can easily just rejoin but still, it's a rather annoying issue since anyone can just kick me out of my own server essentially if they knew this bug was a thing. We tried to reproduce with someone else but to our knowledge, no one else on my server has been able to reproduce it. It's just only me getting it, we even attempted to see if they did similar things that I have done on the server to reproduce and still nothing.

So, I don't know what is going on or if this is a conflict error happening between mods since multiple mods were mentioned (Cloudstorage and Big Brain being the first two, and since your mod only has the Buckler as an item, I was more comfortable with removing it from the server to see if I would crash or not).

Note: The issue doesn't appear at all in SP, only in a modded server. I have read the logs several time and still can't fully understand what is causing what to happen. All I knew that a specific vanilla element isn't being found while the Spyglass is being used (the follow range for mobs specifically).

I put the section of the log below where the error is posted.

[2022-10-07-1.log](https://github.com/seymourimadeit/Big-Brain/files/9730498/2022-10-07-1.log)

**Comment by seymourimadeit** [comment]
Test it with the same conditions (wearing cursed ring and spyglass) in 1.19 using the same mods affected (big brain and enigmatic legacy)

**Comment by Jusey1** [comment]
Enigmatic Legacy isn't on 1.19.2 yet.

**Comment by seymourimadeit** [comment]
> Enigmatic Legacy isn't on 1.19.2 yet. (Kinda one of the few reasons why I am on a 1.18.2 server currently).

Very sorry for the late response but until this issue can be recreated on 1.19.2 this will have to be closed due to the fact 1.18.2 is unsupported.
