### ISSUE TITLE
[1.19.2] Crash on launch caused by Big Brain

### ISSUE THREAD

**Issue by GoldenDarius** [seymourimadeit/Big-Brain#32]
I'm using the latest version of Big Brain, with the latest version of Forge (43.1.34) and I got a crash on launch
![image](https://user-images.githubusercontent.com/75396163/194709112-da3e4985-d055-4c3f-aff2-401b1250fd59.png)

here's the crash-report though.
[crash-2022-10-08_13.01.13-fml.txt](https://github.com/seymourimadeit/Big-Brain/files/9739286/crash-2022-10-08_13.01.13-fml.txt)

**Comment by seymourimadeit** [comment]
Does this crash happen repeatedly? Sometimes forge just does this and a quick restart fixes it.

**Comment by GoldenDarius** [comment]
I haven't tried, I honestly assumed it was because that forge version had literally just come out and I decided to update it.. I'm pretty sure it doesn't break with 43.1.33
