### ISSUE TITLE
[1.19.4] - Client Crash with Kobolds Mod's Skelebold

### ISSUE THREAD

**Issue by Jusey1** [seymourimadeit/Big-Brain#37]
In the 1.19.4 version of mod, and I assume later (once I get to porting my stuff to 1.20 that is) there is a new conflict crash where if my Skelebolds are loaded, it causes a client crash. It's a pretty straight forward crash though. Essentially, the SkeletonModel is being casted onto my Skelebolds when they are using their own model, thus crashing the game as it is unable to do what your Event is wanting to do in "BigBrainClientEvents". 

Seems to be happening in "onEntityRenderPost" where you check for an instanceof Skeleton but didn't check for what model is being rendered. Probably a quick  "if (event.getRenderer().getModel() instanceof SkeletonModel skeleModel)" would do the trick instead cause then it won't cast the SkeletonModel onto my Skelebold since event.getRenderer().getModel() will return SkeleboldModel instead of SkeletonModel and be unable to past that if check.

**Comment by Jusey1** [comment]
Just want to add that this crash is happening on 1.20 as well but I am assuming the 1.20 version just hasn't been updated yet with the change done to the 1.19.4 version.

**Comment by seymourimadeit** [comment]
fixed
