### ISSUE TITLE
Pillager Server Crash

### ISSUE THREAD

**Issue by WenXin20** [seymourimadeit/Big-Brain#4]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Big Brain v1.1.1`

My server crashed during world load after adding this mod.
[Crash Report](https://gist.github.com/WenXin20/8e988b86ba11509a37d44e8f795ba62b)

**Comment by WenXin20** [comment]
Was this published in the hotfix? I got the crash again.
https://gist.github.com/WenXin20/e09bc767ac41135517ae04d8c1893098

**Comment by seymourimadeit** [comment]
Redownload the mod again and see if it still crashes.
