### ISSUE TITLE
[1.20.1 fml] Entities randomly perform jumps

### ISSUE THREAD

**Issue by Cixon** [seymourimadeit/Big-Brain#42]
ParkourGoal.start is either bugged or not yet polished. I say this because I've noticed all vanilla entities (some modded) have a delayed aggroed towards players and they also perform unnecessary parkour attempts (jumps).

I understand I can disable this in a config but figured I'd bring this to your attention as I'd love to use the parkour mechanic but sadly it's not as functional as I'd hope especially in exchange for less performance.

Wonderful work thus far, this project is approaching its 3 year anniversary, very happy to see it still alive! :-)

**Comment by seymourimadeit** [comment]
fixed in dev
