### ISSUE TITLE
[1.20.1] Lag with Big Brain once more mobs show up, maybe has something to do with parkour?

### ISSUE THREAD

**Issue by BugmanBugman** [seymourimadeit/Big-Brain#43]
https://spark.lucko.me/AUvM5ZGI6X
Spark log attributes it to "tallestegg.bigbrain.common.entity.ai.goals.ParkourGoal.pickCandidate()28.47%", might be something there? I tested my server off and on without it, and the lag only happens with big brain
![2023-09-17_14 31 54](https://github.com/seymourimadeit/Big-Brain/assets/40730042/814a1d9b-532e-4601-ad6e-d0ad121c681b)

**Comment by seymourimadeit** [comment]
fixed in dev
