### ISSUE TITLE
[1.20.1] Crash with 1.7.3 on server startup

### ISSUE THREAD

**Issue by BugmanBugman** [seymourimadeit/Big-Brain#44]
https://hastebin.skyra.pw/aremunumiv.nestedtext

**Comment by seymourimadeit** [comment]
update your forge

**Comment by BugmanBugman** [comment]
To which version? I'm on the latest version of neoforge 47.1.76

**Comment by seymourimadeit** [comment]
update to the latest version of regular forge for now

i'll update to neoforge post 1.20
