### ISSUE TITLE
Starting the game crashed!

### ISSUE THREAD

**Issue by Qee1y** [seymourimadeit/Big-Brain#47]
mod：1.7.3
mc：1.20.1 
forge ：47.1.3 

[crash-2023-10-10_22.18.32-client.txt](https://github.com/seymourimadeit/Big-Brain/files/12858299/crash-2023-10-10_22.18.32-client.txt)

**Comment by seymourimadeit** [comment]
Doesn't look to be on this mods side

**Comment by Qee1y** [comment]
当我加入bigbrain mod时，无法启动，跟sinytra-connector是否不兼容?

**Comment by seymourimadeit** [comment]
> nytra-connector

Try updating your forge and testing these mods alone. The reason I'm saying it's most likely not this mod's problem is because the crash references a mod named "snifferplus" with no mention of big brain.

**Comment by Qee1y** [comment]
Okay, thank you
