### ISSUE TITLE
[Compatability] Mob hit sound is changed when installed with CriticalLib

### ISSUE THREAD

**Issue by ChiefLogan3010** [seymourimadeit/Big-Brain#48]
When hitting an entity with both mods, the hit sound is changed to a deeper, energy shield-like sound. I'm pretty sure I've heard it elsewhere in vanilla but I can't remember where. I'm not sure which of the two mods is causing the issue, but it only happens when both are loaded. I have also created a bug report on the CriticalLib Github here: https://github.com/hamusuke0323/CriticaLibForge/issues/1

Versions used:
Minecraft 1.19.2
Forge 34.3.2
bigbrain-1.19.2-1.6.7
criticalib-forge-1.19.2-1.0.0

Steps to reproduce:

Download Big Brain & CriticalLib
Load up a world
Hit an entity
Sound will be different to usual sound.

**Comment by seymourimadeit** [comment]
Sorry but I do not support 1.19.2 anymore.

The sound effect comes from big brain but this mod also doesn't really change anything about how critical hits work so the issue is more likely with the other mod, the features related to the sound effect have also been moved to another mod in 1.20.
