### ISSUE TITLE
Something about EntityEventEyeHeight

### ISSUE THREAD

**Issue by Nekkok** [seymourimadeit/Big-Brain#51]
Crashing immediately with latest version of Big Brain installed. Maybe a compatibility issue?
[crash-2024-05-07_11.25.04-fml.txt](https://github.com/seymourimadeit/Big-Brain/files/15233532/crash-2024-05-07_11.25.04-fml.txt)

**Comment by flowerfugue** [comment]
From the looks of it, something changed in a later version of forge/neoforge and now the mod doesnt work past that version. Should be a pretty simple update but don't think I can do it soon cause of assignments 😔 If @seymourimadeit has time but I think he's just as busy!

Nevertheless, we know about the bug so now it will get fixed at some point; thanks for reporting!
