### ISSUE TITLE
Crash related to the "Find Shelter" from Big Brain 1.2.0.

### ISSUE THREAD

**Issue by Jusey1** [seymourimadeit/Big-Brain#7]
I've been getting consistent crashes all related to the same thing which is related to the new "Find Shelter" script for animals. However, it isn't the script itself that is causing the crash but rather it is attempting to do this on a rat from Alex's Rats mod (V7.1.1). So, a quick hotfix might be in order to disable this new script from working on modded entities perhaps? Or at least a config option to disable it?

Note: this is base on how I read the crash log, correct me if I am wrong.

[crash-2021-04-07_18.02.01-server.txt](https://github.com/seymourimadeit/Big-Brain/files/6274798/crash-2021-04-07_18.02.01-server.txt)

Sorry for bringing this up!

**Comment by seymourimadeit** [comment]
Theres a black list in the config.

**Comment by seymourimadeit** [comment]
Theres a black list in the config. Next time check the config before saying "theres no config option to disable it", I will see if I can make a fix on my side.

**Comment by seymourimadeit** [comment]
hotfix released

**Comment by Jusey1** [comment]
> 
> 
> Theres a black list in the config. Next time check the config before saying "theres no config option to disable it"

I did check the config first and foremost matey. Sure, I didn't delete my config and generated a new one, that is on me but I did check the config and the new option wasn't added which usually happens. So now that I know about this, I'll regenerate the config.
