### ISSUE TITLE
Some suggestions on "find shelter"

### ISSUE THREAD

**Issue by pwigary** [seymourimadeit/Big-Brain#8]
1. A sperate blacklist for weather and night
2. Biome blacklist, mainly for desertry biomes (other mods have mobs spawn both in desert and savanna) or makes AI gives up after a set amount of time?
3. A minimum y value to trigger the goals (maybe it already is but the AI looks a bit wonky underground)

:)

**Comment by seymourimadeit** [comment]
Suggestions should be sent on the discord, not on this github page.
